### PR TITLE
Plone5

### PR DESCRIPTION
**Pull request by davilima6**
We can still improve some things like moving JS/CSS registrations from legacy bundle to a package one, with proper resources and `merge_with` etc but since it now works fully in Plone 5 I'd vote for a release.

### CODE REVIEW

**Comment by avoinea** [comment]
@davilima6 Thank you for your contribution. Still, it seems that your pull request breaks the tests: http://ci.eionet.europa.eu/job/eea.annotator-www/159/console

I also can not add a Plone 4 site with EEA Annotator enabled, either install it after.
```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
__traceback_info__: ('eea.annotator',)
Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
__traceback_info__: profile-eea.annotator:default
Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
__traceback_info__: plone.app.registry
Module plone.app.registry.exportimport.handler, line 49, in importRegistry
Module plone.app.registry.exportimport.handler, line 94, in importDocument
Module plone.app.registry.exportimport.handler, line 281, in importRecords
Module zope.dottedname.resolve, line 38, in resolve
ImportError: No module named IBundleRegistry
```

**Comment by davilima6** [comment]
@avoinea, this needs to be released for Plone 5 from this branch. We may be able to keep master dual version but that'd probably mean creating a plone5 GS profile - similar to Plone's `dependencies` - and install it via setuphandlers.py only when Plone > 5. Can you think of other paths?

I'd be +1 to have a release before this is ready, since it's 100% working in P5. That traceback only happens in P4.

**Comment by avoinea** [comment]
The problem is that it doesn't seems to be fully functional in Plone 5, either:

```
$ docker run -it --rm --name=plone5 \
             -v $(pwd)/eea.annotator:/plone/instance/src/eea.annotator \
             -e BUILDOUT_EGGS=eea.annotator \
             -e BUILDOUT_DEVELOP=src/eea.annotator \
             -p 8080:8080 \
         plone/plone:5 fg
```

I managed to install it, but I can not add inline comments

**Comment by davilima6** [comment]
Is there any error on the console?

Could you please:
1. Go to `http://localhost:8080/Plone/@@resourceregistry-controlpanel`
2. Click Development Mode
3. Click Develop JS in `plone-legacy` bundle.
4. Click Save.
5. Reload homepage again and test product.

**Comment by davilima6** [comment]
Btw, here's another path for achieving dual compatibility: https://github.com/collective/example.p4p5/commit/e0b345fe9618ce297420669859b880e1a806fffb

**Comment by avoinea** [comment]
Ha, it works with Development Mode Enabled.

**Pull request merged**
